steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'clone-sherlock'
  args:
    - clone
    - 'https://github.com/sherlockify/sherlock'
  dir: './run-sherlock'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  id: 'move-sherlock-require'
  args:
    - -c
    - |
      cat ./run-sherlock/sherlock/requirements.txt >> ./run-sherlock/requirements.txt


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  waitFor:
    - 'clone-sherlock'
    - 'move-sherlock-require'
  args:
    - gcloud
    - functions
    - deploy
    - sherlock
    - --region=us-west1
    - --source=./run-sherlock
    - --entry-point=endpoint
    - --memory=32768MB
    - --timeout=120
    - --trigger-http
    - --runtime=python311
    - --allow-unauthenticated
    - --gen2